model:
  learning_rate: 5.0e-6
  target: models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 8
    kl_weight: 1.0e-6
    ddconfig:
      double_z: true
      z_channels: 8
      resolution: 32 # 64 / 2 s2c
      in_ch: 8
      out_ch: 8
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 4
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.1
      sigmoid_out: true
    disc_config:
      disc_start: 500000000
      disc_weight: 0.5
      disc_loss: "vanilla"
      disc_conditional: false
      disc_factor: 0
      disc_in_channels: 8
      disc_num_layers: 3
data:
  batch_size: 64
  num_workers: 4
  wrap: true